# Algorithm 2 Data acquisition process with missing values


# This algorithm calls a function which generates missing values,
# randomly selecting elements, substracting them from the 'undetected' U column.

# INPUT : df = dataframe generated by missing values algo
# prop = proportion of missing values desired (0 < prop < 1 )
gen.mval.fun <- function(df,prop){ 
  # inner function, select random elements and take their sum
  random_row_sum <- function(row) {
    # select 2 val
    selected_indices <- sample(length(row), floor(prop*length(row)))
    selected_values <- row[selected_indices]
    sum(selected_values)
    return(list(sum(selected_values),selected_indices))
  }
  # create a sum vector 
  sum.vec <- c()
  for (i in 1:nrow(df)){
    random.row.o <- random_row_sum(df[i,])
    sum.vec[i] <- random.row.o[[1]]
    df[i,c(random.row.o[[2]])] <- NA
  }
  output <- cbind(df,sum.vec) %>% as_tibble()
  return(output)
}

# Final function 

fun.mval <- function(tibble,propmissing){
  output <- gen.mval.fun(tibble[-ncol(tibble)],prop = propmissing)
  output$U <- output$sum.vec + tibble$U
  output$sum.vec <- NULL
  return(output)
}

